# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'Free Trial(18d635e6-beae-482d-bbe1-e1d1f008bdca)'
    subscriptionId: '18d635e6-beae-482d-bbe1-e1d1f008bdca'
    location: 'North Europe'
    templateLocation: 'URL of the file'
    csmFileLink: '$(Build.SourcesDirectory)/.pipelines/azure-templates/resource_group.template.json'
    csmParametersFileLink: '$(Build.SourcesDirectory)/.pipelines/azure-templates/resource_group.parameters.json'
    deploymentMode: 'Incremental'
